/*
 * module function declaration for library dummies header (autogenerated)
 */

#include "dummies_module.h"

int dummies_mod_init(ubx_node_info_t* ni)
{
  int ret;
  ret=receiver_mod_init(ni);
  if(ret!=0)
    goto out;

out:
   return ret;
}

void dummies_mod_cleanup(ubx_node_info_t* ni)
{
  receiver_mod_cleanup(ni);
}

