/*
 * module function declaration for library schedmod header (autogenerated)
 */

#include "schedmod_module.h"

int schedmod_mod_init(ubx_node_info_t* ni)
{
  int ret;
  ret=sseq_mod_init(ni);
  if(ret!=0)
    goto out;

out:
   return ret;
}

void schedmod_mod_cleanup(ubx_node_info_t* ni)
{
  sseq_mod_cleanup(ni);
}

